### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by ipeke** [ipeke/STEM-Day-Collaboration#1]
- [ ] Get list of dog names by address
- [ ] Geocode address to lat/log using google maps API
- [ ] Plot lat/long of dogs on map
- [ ] Overlay NYC zipcode boundaries
- [ ] combine lat/long data with zipcode data
- [ ] `group_by(zipcode, name) %>% summarize(n = n())`

- [ ] make it shiny
